### ISSUE TITLE
ICKeyer - Not responding on IC705 in BT mode.

### ISSUE THREAD

**Issue by PyroBritUK** [armel/M5HamRadio#18]
Hi.

Firstly ICSMeter and ICMultiMeter both work well on my M5 Stack Basic.

I have added ICKeyer to the SD card.
After a reboot it loads and the 705 responds by showing that a BT connection is established.
The M5 screen will either display all the buttons but every button will say "Menu" and none of them respond or it will display half of the buttons as "T1, T2, T3" and the rest as "MENU". AGain the M5 will not respond,
Changing bands on the 705 does not make any changes to the M5 screen.

The 705 is at latest firmware 1.32
ICKeyer = v1.0.3

M5Burner serial text is below:

`FROM M5Burner]COM11 opened.
ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1184
load:0x40078000,len:12812
load:0x40080400,len:3032
entry 0x400805e4
E (449) psram: PSRAM ID read error: 0xffffffff
LittleFS/DXTracker.bin
LittleFS/ICMultiMeter.bin
LittleFS/ICSMeter.bin
----------
SD/ICKeyer.bin
----------
----------
SD/IC705BT.ini
SD/DXTracker.ini
----------
/.backup.ini
wifi-id
wifipassword
705
A4
1
30 31 7D 33 C5 80 
115200
http://192.168.1.32
1234
Wifi Client Disconnected
Wifi Client Connected
192.168.0.234
Refresh mode
GetMode
GetTX
GetMode`

I'll see if I can get some screenshots for you:

Kind regards

Nick.W

**Comment by PyroBritUK** [comment]
![IMG_6473](https://user-images.githubusercontent.com/130462397/231154144-94c927e3-b2c3-48c7-9534-82d142d5503d.jpeg)
![IMG_6472](https://user-images.githubusercontent.com/130462397/231154159-20685e19-2d80-4980-b3c5-92d2cc20a2f6.jpeg)

photos attached showing the two possible outcomes the screen can have after the 705 confirms BT connection.

**Comment by armel** [comment]
Hello Nick,

Thank you for your message.
I just checked on a BASIC and indeed, I observe the same problem. So thank you very much. I'll look into it when I have time and let you know.
So, stay tuned ;)

73'

Armel F4HWN

**Comment by armel** [comment]
Hello Nick,

Could you try to download the new version (1.0.4) ?
Direct link https://github.com/armel/M5HamRadio/raw/main/firmwares/ICKeyer.bin

It was a memory problem due to the use of bluetooth. Bluetooth consumes a lot of memory. 

Note that this application is very difficult to develop and offers poor stability. I would need more time to fix it and stabilize it. But I am too busy. 

Nevertheless, it should work a bit better. But I know that there are still many bugs.

73'

Armel F4HWN.

**Comment by PyroBritUK** [comment]
Hi Armel,

That is much better.  The button tops change depending on if I choose FM/SSB or CW.  I can access the menu and change brightness and beep volume.

Unfortunately there is another error now.

I can choose a button and select 1 play or repeat play.
I can start the playback and the 705 starts to play the recording on repeat even if the M5 is set to 1 play.
Once play has started the M5 changes to "stop" but it does not respond. All keys are frozen.
To stop the 705 playing the recording I have to reboot the M5.

The onscreen memory buttons are only selectable using the three physical buttons. Is that a limit of the M5 Basic?
I answer my own questions. Yes, the M5 Basic is not touch screen.

Many thanks for your help.

Nick.W - M0NYY

**Comment by armel** [comment]
Hello Nick,

Yeah I know, there are many problems with this app 🤔 It's a real nightmare. 

Could you try to download the new version (1.0.5) ?

Direct link https://github.com/armel/M5HamRadio/raw/main/firmwares/ICKeyer.bin

About screen limitation, yes, the M5 Basic is not a touch screen. But no regret, the touch screen on the M5 Core2 is really hard to control. Don't expect to have the responsiveness of a smartphone screen with an M5 Core2. It's still a (very) low-end touchscreen.  It's easier to navigate with the buttons. 

Next month, a new M5 Core S3 will be available. I don't know if the touch screen will be more efficient. But I hope I could try it.

73'

Armel F4HWN.

**Comment by PyroBritUK** [comment]
Hi Armel,

I tried the new download but the version displayed on the M5 screen is still showing as v1.04. It still freezes after the audio playback starts after the screen changes to a stop button. The version text continues to scroll even after the buttons have frozen.

Thanks for the update about the M5 Core3. I feel that donating you a glass of wine for your support and work is too little. Perhaps I can donate you an M5 Core3 when they become available?

kind regards

Nick.W - M0NYY

**Comment by armel** [comment]
Hi Nick,

Humm, it may be a cache problem on your browser ? It's really version 1.0.5
I have just tested again and you can see 1.0.5.
Note that if you have put the new binary on your SD card, you must also **reload** it with the **binLoader** at startup, by selecting it.

Thanks for your message and your support. 

Regards and 73'

Armel F4HWN

**Comment by armel** [comment]
New release 1.0.8 (improve stability, scroll, BT support, screensaver, disconnect detection, etc.).
It seems to me that this Keyer is starting to become much more stable 🤔 
Tell me 😌

Regards and 73'

Armel F4HWN

**Comment by PyroBritUK** [comment]
Hi Armel,

sorry for the delay in reply. It’s been a busy week at work.  You were right. I had not loaded the file from the SD card.  V1.05 works very well now.
I shall try v1.08 later on Friday as I will be demonstrating to the local radio club on Monday.

regards

Nick.W - M0NYY

**Comment by armel** [comment]
Hi Nick,

No problem 🤗 The last version v1.0.8 seems to work well. I play with it every day.
I even made a little video demonstrating how it works (video in French, sorry).

https://youtu.be/eI4Qy2YkNs4?t=288 

Regards,

Armel F4HWN.
