### ISSUE TITLE
M5HamRadio Function

### ISSUE THREAD

**Issue by marmatBCN** [armel/M5HamRadio#2]
Hi Armel,
Has the functionality of the programs changed or just the installation method?

**Comment by armel** [comment]
Hello 🙋🏼‍♂️

ICSMeter, ICMultiMeter and DXTracker are all in version 2.0.0 with the latest fixes and code improvements. Now, if you are happy with the old versions, there are no big changes except for a redesign of the Bin Loader, the addition of the Ini Loader, the change of the battery design, etc. In any case, you can try and go back if needed by recompiling the old versions.

Armel F4HWN.

**Comment by Matt-BW** [comment]
Works wonderfully! Fantastic work Armel! Almost tempted to get the upgraded M5stack for the keyer. Really fantastic suite of software.

**Comment by armel** [comment]
Thank you ;)
