### ISSUE TITLE
M5 Core 2 Touch Screen only - ini file will not load

### ISSUE THREAD

**Issue by fbeider** [armel/M5HamRadio#33]
Hello

I have a M5 core2 touch screen only (no physical buttons).  

Using M5 burner I installed .8 for the core 2.

Get the error message Ini file does not exist
failed to load config file

Here is the ouptut  of the serial monitor.  The .ini file appears to be loading from the SD card

rst:0x1 (POWERON_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1344
load:0x40078000,len:13924
ho 0 tail 12 room 4
load:0x40080400,len:3600
entry 0x400805f0
----------
LittleFS/DXTracker.gz
LittleFS/ICKeyer.gz
LittleFS/ICMultiMeter.gz
LittleFS/ICSMeter.gz
----------
----------
----------
----------
SD/IC705BT.ini
----------
/.backup.ini
[FROM M5Burner] Serial Port Disconnected.

**Comment by armel** [comment]
Hello,

Take a look to the README again : https://github.com/armel/M5HamRadio#ini-loader
You need to select your ini config file during the Ini Loader step (blue progress bar). 

Armel F4HWN.

**Comment by fbeider** [comment]
I cannot select a config file as there are no hardware buttons on M5 Core 2 touch screen only.   No buttons appear on the screen to touch.  I do see the inil oader v.07 on the screen

**Comment by armel** [comment]
Sure, of course you've got (virtual) buttons. Take a look a this image...

![Core2](https://user-images.githubusercontent.com/127889/236472188-bc62fd21-7d69-4b08-8ae6-5ab5ad47b6ad.png)

Armel F4HWN.

**Comment by fbeider** [comment]
![PXL_20230505_132921079 MP 1](https://user-images.githubusercontent.com/132420658/236472040-6f4a5fe7-e655-4dad-8baa-813fda722777.jpg)
I see the issue.  When I take photo with Camera it "sees" the buttons.  But my eye cannot see them

**Comment by armel** [comment]
Ok, so during the Ini Loader step (blue progress bar), 

1 - touch middle virtual button to enter into Ini Loader
2 - use left / right virtual buttons to choose your ini file.
3 - touch middle virtual button to select it.

Armel F4HWN.

**Comment by fbeider** [comment]
I got it working.

Thank You!

**Comment by armel** [comment]
Good news.
Thank you.
I close this issue.

73'

Armel F4HWN
