### ISSUE TITLE
IC7000

### ISSUE THREAD

**Issue by AndyWBing** [armel/M5HamRadio#58]
Hi Armel. I have the meter working with my IC705 by bluetooth and my IC7300 using the bluetooth adapter, it's great thanks.

My question is, should I be able to also get it working with my IC7000 using the same bluetooth adapter? I assume I need to create a new .ini file the same as the file for the IC7300, but just change the radio name to IC7000 and the change the Icom address to match that of the IC7000 which is 70h?

Regards
Andy
(G7PAZ)

**Comment by armel** [comment]
Hi Andy,

It's not that simple. 
I don't know if all the CI-V commands I use in my project are available on this IC-7000. It may also require calibration of the returned values. Of course, you can always test.

73'

Armel F4HWN.
