### ISSUE TITLE
ability to add/modify DX Cluster Data

### ISSUE THREAD

**Issue by magnetus26** [armel/M5HamRadio#68]
hello, 
first excellent job, I really enjoy you project keep up the good work.
now is it there a way to modify the DX Cluster data? I will like to see USA cluster or a way to add/modify the cluster to anyother besides the one built in.
best regards,
Miguel
73's de KP4MI

**Comment by armel** [comment]
Hello Miguel,

Thanks for your message. No, it's not possible to add or modify the DX cluster data. It would be a bit complicated to do, as the data format is often different from one cluster to another. 

Best regards,

Armel.

73' de F4HWN

**Comment by magnetus26** [comment]
thanks for a quick reply
