### ISSUE TITLE
Will it work on M5stack Basic old version with 4MB flash?

### ISSUE THREAD

**Issue by BI3QXJ** [armel/M5HamRadio#70]
will this app work on m5stack basic with 4MB (before 2020.6)? could I flash only ICmeter on my device?

**Comment by armel** [comment]
Hello. No, not enough memory with only 4MB. My apologies.

**Comment by BI3QXJ** [comment]
> Hello. No, not enough memory with only 4MB. My apologies.

thanks for your reply! 73!
