### ISSUE TITLE
Support for M5Stack knob?

### ISSUE THREAD

**Issue by luarvique** [armel/M5HamRadio#83]
M5Stack also produces [this](https://shop.m5stack.com/products/m5stack-dial-esp32-s3-smart-rotary-knob-w-1-28-round-touch-screen). Any plans to run the apps on it, maybe even using the knob to control frequency, volume, etc?

**Comment by armel** [comment]
No, M5Dial doesn't include an SD card reader. And I need it. 
There's no internal battery either. 

Finally, I've already developed a project on it : [M5DialSun](https://github.com/armel/M5DialSun).
