### ISSUE TITLE
ICSMultiMeter for 7610

### ISSUE THREAD

**Issue by pcpackrat** [armel/M5HamRadio#89]
I have a vague memory that I was trying to manipulate the CI-V to get this to work with the 7610 but now I cannot find any code to start again on it.

Is this no longer available?

**Comment by armel** [comment]
Hello,

Thank you for your message.
I suggest you read these [disclaimers](https://github.com/armel/M5HamRadio?tab=readme-ov-file#disclaimers).

Regards,

Armel F4HWN

**Comment by pcpackrat** [comment]
I guess I'll search my old drive again then.

**Comment by armel** [comment]
The old source code is still [available](https://github.com/armel/ICMultiMeter), but it's totally obsolete.
